import type { LanguageType } from '@/helpers/locale/locale';

const copy = {
  ru: {
    brand: 'CMS Labs',
    overview: 'Обзор',
    topology: 'Топология',
    assignment: 'Задание',
    refresh: 'Обновить',
    stop: 'Остановить стенд',
    running: 'Работает',
    preparing: 'Запускается',
    failed: 'Ошибка',
    degraded: 'Есть проблемы',
    stopping: 'Останавливается',
    labStand: 'Лабораторный стенд',
    currentEnvironment: 'Текущее состояние учебной среды',
    standState: 'Состояние стенда',
    nodes: 'Узлы',
    user: 'Пользователь',
    uptime: 'Время работы',
    active: 'активно',
    environment: 'Параметры среды',
    namespace: 'Namespace',
    labPath: 'Материалы',
    testPath: 'Набор проверок',
    revision: 'Версия задания',
    accepted: 'Ресурсы приняты Kubernetes',
    components: 'Компоненты стенда',
    component: 'Компонент',
    kind: 'Тип',
    address: 'Адрес',
    state: 'Состояние',
    restarts: 'Рестарты',
    valueCopied: 'Значение скопировано',
    copyValueHint: 'Нажмите, чтобы скопировать значение',
    ready: 'Готов',
    notReady: 'Запускается',
    noTopology: 'Топология ещё не создана',
    noComponents: 'Компоненты появятся после применения топологии.',
    events: 'Ход запуска',
    sessionCreated: 'Сессия создана',
    desiredAccepted: 'Описание стенда принято',
    topologyReady: 'Топология готова',
    workspaceReady: 'JupyterLab готов',
    waiting: 'Ожидание',
    topologyHint: 'Нажмите узел, чтобы открыть действия и терминал',
    topologyLoading: 'Топология разворачивается',
    topologyLoadingDescription: 'Схема появится сразу после готовности Clabernetes.',
    workspaceLoading: 'JupyterLab запускается',
    workspaceLoadingDescription: 'Рабочая область откроется здесь автоматически.',
    workspaceError: 'Не удалось открыть JupyterLab',
    workspaceRedirecting: 'Открываем JupyterLab',
    workspaceRedirectingDescription: 'Получаем новый одноразовый доступ к рабочей области…',
    workspaceRedirectError: 'Не удалось получить доступ к JupyterLab',
    openExternal: 'Открыть в новой вкладке',
    retry: 'Повторить',
    validations: 'Результаты проверок',
    completed: 'Выполнено',
    of: 'из',
    noChecks: 'Проверки ещё не запускались',
    noChecksDescription: 'Когда стенд будет готов, запустите проверку — результат и реальные логи появятся здесь.',
    runCheck: 'Запустить проверку',
    checking: 'Проверяем…',
    lastCheck: 'Последняя проверка',
    pending: 'Ожидает',
    passed: 'Пройдена',
    checkFailed: 'Не пройдена',
    checkRunning: 'Выполняется',
    duration: 'Длительность',
    report: 'Отчёт',
    output: 'Вывод',
    score: 'Оценка',
    checkerJob: 'Автоматическая проверка',
    checkerUnavailable: 'Checker не вернул структурированный результат.',
    collapseChecks: 'Скрыть проверки',
    expandChecks: 'Показать проверки',
    sessionError: 'Не удалось запустить лабораторную сессию',
    invalidSession: 'В адресе отсутствует идентификатор попытки.',
    backHome: 'Вернуться',
    showOnTopology: 'Показать на топологии',
    workspaceMenu: 'Управление стендом',
    switchToLight: 'Включить светлую тему',
    switchToDark: 'Включить тёмную тему',
    changeLanguage: 'Switch to English',
    restartTopology: 'Перезапустить топологию',
    restartTopologyDescription: 'Все узлы стенда будут перезапущены. Текущие конфигурации сохранятся.',
    wipeTopology: 'Очистить топологию',
    wipeTopologyDescription: 'Все узлы будут возвращены в исходное состояние. Несохранённые настройки пропадут.',
    startTour: 'Обучение по интерфейсу',
    actionSuccess: 'Команда принята',
    actionError: 'Не удалось выполнить команду',
    tourWelcomeTitle: 'Рабочая область лаборатории',
    tourWelcomeDescription: 'Здесь собраны стенд, топология, JupyterLab и результаты автоматических проверок.',
    tourTabsTitle: 'Рабочие вкладки',
    tourTabsDescription: 'Переключайтесь между обзором состояния, сетевой топологией и заданием в JupyterLab.',
    tourWorkspaceTitle: 'Основная рабочая область',
    tourWorkspaceDescription:
      'Здесь отображается выбранный инструмент. Состояние сохраняется при переключении вкладок.',
    tourChecksTitle: 'Автоматические проверки',
    tourChecksDescription: 'Запускайте checker, раскрывайте результаты и переходите от ошибки к узлу топологии.',
    tourControlsTitle: 'Управление стендом',
    tourControlsDescription:
      'В этом меню доступны обновление, перезапуск и очистка топологии, а также повторное обучение.',
    tourAssignmentTitle: 'Задание и JupyterLab',
    tourAssignmentDescription:
      'JupyterLab открывается внутри рабочей области и при необходимости — в отдельной вкладке.',
    tourNext: 'Далее',
    tourPrevious: 'Назад',
    tourDone: 'Начать работу',
    tourSkip: 'Пропустить',
    tourStep: 'Шаг',
    stopTitle: 'Завершить лабораторную работу?',
    stopDescription: 'После завершения Kubernetes-сессия и её рабочее хранилище будут удалены.',
    stopTeacherChecked: 'Преподаватель проверил выполненную работу или результат проверки уже зафиксирован.',
    stopFilesExported: 'Я сохранил нужные файлы в формате .ipynb и/или HTML на свой компьютер.',
    stopIrreversible: 'Я понимаю, что завершённую лабораторную работу невозможно восстановить.',
    stopCancel: 'Продолжить работу',
    stopConfirm: 'Завершить и удалить',
    stopWarning: 'Это необратимое действие'
  },
  en: {
    brand: 'CMS Labs',
    overview: 'Overview',
    topology: 'Topology',
    assignment: 'Assignment',
    refresh: 'Refresh',
    stop: 'Stop lab',
    running: 'Running',
    preparing: 'Starting',
    failed: 'Failed',
    degraded: 'Degraded',
    stopping: 'Stopping',
    labStand: 'Laboratory environment',
    currentEnvironment: 'Current state of the learning environment',
    standState: 'Environment status',
    nodes: 'Nodes',
    user: 'User',
    uptime: 'Uptime',
    active: 'active',
    environment: 'Environment details',
    namespace: 'Namespace',
    labPath: 'Lab materials',
    testPath: 'Check suite',
    revision: 'Task revision',
    accepted: 'Resources accepted by Kubernetes',
    components: 'Environment components',
    component: 'Component',
    kind: 'Type',
    address: 'Address',
    state: 'State',
    restarts: 'Restarts',
    valueCopied: 'Value copied',
    copyValueHint: 'Click to copy this value',
    ready: 'Ready',
    notReady: 'Starting',
    noTopology: 'Topology has not been created yet',
    noComponents: 'Components will appear after the topology is applied.',
    events: 'Startup progress',
    sessionCreated: 'Session created',
    desiredAccepted: 'Environment definition accepted',
    topologyReady: 'Topology ready',
    workspaceReady: 'JupyterLab ready',
    waiting: 'Waiting',
    topologyHint: 'Select a node to open actions and its terminal',
    topologyLoading: 'Topology is starting',
    topologyLoadingDescription: 'The diagram will appear as soon as Clabernetes is ready.',
    workspaceLoading: 'JupyterLab is starting',
    workspaceLoadingDescription: 'The workspace will open here automatically.',
    workspaceError: 'Could not open JupyterLab',
    workspaceRedirecting: 'Opening JupyterLab',
    workspaceRedirectingDescription: 'Requesting fresh one-time access to the workspace…',
    workspaceRedirectError: 'Could not obtain access to JupyterLab',
    openExternal: 'Open in a new tab',
    retry: 'Retry',
    validations: 'Validation results',
    completed: 'Completed',
    of: 'of',
    noChecks: 'No checks have run yet',
    noChecksDescription: 'Run validation when the environment is ready. Real results and logs will appear here.',
    runCheck: 'Run validation',
    checking: 'Checking…',
    lastCheck: 'Last check',
    pending: 'Pending',
    passed: 'Passed',
    checkFailed: 'Failed',
    checkRunning: 'Running',
    duration: 'Duration',
    report: 'Report',
    output: 'Output',
    score: 'Score',
    checkerJob: 'Automated validation',
    checkerUnavailable: 'The checker did not return a structured result.',
    collapseChecks: 'Hide checks',
    expandChecks: 'Show checks',
    sessionError: 'Could not start the laboratory session',
    invalidSession: 'The attempt identifier is missing from the URL.',
    backHome: 'Go back',
    showOnTopology: 'Show on topology',
    workspaceMenu: 'Environment controls',
    switchToLight: 'Switch to light theme',
    switchToDark: 'Switch to dark theme',
    changeLanguage: 'Переключить на русский',
    restartTopology: 'Restart topology',
    restartTopologyDescription: 'All lab nodes will restart. Their current configurations will be preserved.',
    wipeTopology: 'Wipe topology',
    wipeTopologyDescription: 'All nodes will return to their initial state. Unsaved configuration will be lost.',
    startTour: 'Interface tour',
    actionSuccess: 'Command accepted',
    actionError: 'Could not execute the command',
    tourWelcomeTitle: 'Laboratory workspace',
    tourWelcomeDescription: 'The environment, topology, JupyterLab, and automated validation are available here.',
    tourTabsTitle: 'Workspace tabs',
    tourTabsDescription: 'Switch between environment overview, network topology, and the JupyterLab assignment.',
    tourWorkspaceTitle: 'Main workspace',
    tourWorkspaceDescription: 'The selected tool appears here and remains available while you change tabs.',
    tourChecksTitle: 'Automated validation',
    tourChecksDescription: 'Run the checker, inspect real results, and jump from an error to its topology node.',
    tourControlsTitle: 'Environment controls',
    tourControlsDescription: 'Use this menu to refresh, restart or wipe the topology, and start this tour again.',
    tourAssignmentTitle: 'Assignment and JupyterLab',
    tourAssignmentDescription: 'JupyterLab opens inside the workspace and can also be opened in a separate tab.',
    tourNext: 'Next',
    tourPrevious: 'Back',
    tourDone: 'Start working',
    tourSkip: 'Skip',
    tourStep: 'Step',
    stopTitle: 'Finish this laboratory?',
    stopDescription: 'Finishing will delete the Kubernetes session and its workspace storage.',
    stopTeacherChecked: 'The instructor has reviewed my work, or the validation result has already been recorded.',
    stopFilesExported: 'I saved the required .ipynb and/or HTML files to my computer.',
    stopIrreversible: 'I understand that a finished laboratory cannot be restored.',
    stopCancel: 'Continue working',
    stopConfirm: 'Finish and delete',
    stopWarning: 'This action cannot be undone'
  }
} as const;

export type LabCopy = (typeof copy)['ru'] | (typeof copy)['en'];

export const labCopy = (language: LanguageType): LabCopy => copy[language];
